### PR TITLE
Update to internal 0.74-155

### PR DESCRIPTION
**Pull request by jmbills**
Signed-off-by: Jason M. Bills <jason.m.bills@linux.intel.com>

### CODE REVIEW

**Comment by AlexanderAmelkin** [comment]
Will the update be merged into `intel` branch as well? That's the default one and we're using it for our Purley-Refresh based product.

**Comment by jmbills** [comment]
> Will the update be merged into `intel` branch as well? That's the default one and we're using it for our Purley-Refresh based product.

Not exactly as it is.  We have branched internally to stabilize our release.  This wht branch follows our stable branch.  I plan continue updating the intel branch in the future.  Thanks!

**Comment by AlexanderAmelkin** [comment]
What branch should we use for purley-refresh (wolfpass) in future? Is it still the `intel` branch?

**Comment by jmbills** [comment]
> What branch should we use for purley-refresh (wolfpass) in future? Is it still the `intel` branch?

Yes, in the future the `intel` branch will continue to be the mainline branch (following our internal master branch).

**Pull request merged**
